version: '3'

services:
  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/data/postgres
    networks:
      - bhealth-network

  web:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: dev.txt
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    command: 'sh -c "cp ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"'
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - bhealth-network

  consumer:
    image: bhealth-mvp-backend_web
    restart: always
    env_file: .env
    command: 'sh -c "python3 manage.py start_consumer"'
    volumes:
      - ./:/app
    depends_on:
      - db
      - rabbitmq
    networks:
      - bhealth-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./:/var/lib/rabbitmq/
    networks:
      - bhealth-network

volumes:
  db-data:

networks:
  bhealth-network:
    external: false
