# Generated by Django 3.2.12 on 2023-03-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhealthapp', '0003_remove_notification_is_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_appointment', to='bhealthapp.appointment'),
        ),
    ]
