# Generated by Django 3.2.12 on 2023-03-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhealthapp', '0004_alter_notification_notification_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='city_appointment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_lab',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
