# Generated by Django 3.2.12 on 2023-04-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhealthapp', '0005_auto_20230316_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='lab',
            name='working_days',
            field=models.TextField(default='All working days', max_length=255, null=True),
        ),
    ]
