# Generated by Django 3.2.12 on 2023-05-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhealthapp', '0009_auto_20230512_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
