# Generated by Django 3.2.12 on 2023-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhealthapp', '0010_alter_lab_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='website',
            field=models.CharField(blank=True, default='mywebsite.com', max_length=255, null=True),
        ),
    ]
