# Generated by Django 3.2.12 on 2023-05-12 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhealthapp', '0011_alter_lab_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_city', to='bhealthapp.city'),
        ),
    ]
