# Generated by Django 3.2.12 on 2023-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhealthapp', '0012_alter_lab_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
