# Generated by Django 3.2.12 on 2023-05-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhealthapp', '0013_lab_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='description',
            field=models.TextField(default='Default description'),
        ),
    ]
