# Generated by Django 3.2.12 on 2023-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhealthapp', '0014_lab_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default='My Doctor', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fee',
            field=models.FloatField(default=0.0),
        ),
    ]
