# Generated by Django 3.2.12 on 2023-05-29 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhealthapp', '0015_auto_20230525_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 21, 24, 16, 136086)),
        ),
    ]
