# Generated by Django 3.2.12 on 2023-05-29 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhealthapp', '0016_notification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 21, 27, 16, 681102)),
        ),
    ]
